import { readFileSync } from 'fs';
import { fetchPSI } from './psi.js';
import { loadBaseline, saveBaseline, detectRegressions } from './baseline.js';
import { diagnose } from './diagnose.js';
import { applyAndVerify } from './fix.js';
import {
  getRecentCommits,
  getCommitDiff,
  checkOpenPRs,
  checkOpenIssues,
  createPR,
  createIssue,
} from './github-api.js';

const BASELINE_PATH = '.github/baselines/performance.json';
const CONFIG_PATH = 'perf-agent.config.json';
const PERF_PR_LABEL = 'perf-regression';
const HUMAN_REVIEW_LABEL = 'perf-regression-needs-human';
const DEFAULT_CONFIG = {
  paths: ['/'],
  strategy: 'mobile',
  thresholds: {
    lcp_good_ms: 2500,
    inp_good_ms: 200,
    cls_good: 0.1,
    lcp_increase_ms: 500,
    score_drop: 5,
  },
  lookback_hours: 48,
  default_branch: 'main',
  model: 'gpt-4o',
  ai_diagnosis_enabled: true,
  auto_fix_enabled: false,
  require_psi_api_key: true,
  preview_poll: {
    timeout_ms: 180000,
    interval_ms: 10000,
  },
};

function loadConfig() {
  const config = JSON.parse(readFileSync(CONFIG_PATH, 'utf8'));
  return {
    ...DEFAULT_CONFIG,
    ...config,
    thresholds: {
      ...DEFAULT_CONFIG.thresholds,
      ...(config.thresholds ?? {}),
    },
    preview_poll: {
      ...DEFAULT_CONFIG.preview_poll,
      ...(config.preview_poll ?? {}),
    },
  };
}

function buildContext(config) {
  const owner = process.env.REPO_OWNER;
  const repo = process.env.REPO_NAME;
  const token = process.env.GITHUB_TOKEN;
  const dryRun = process.env.DRY_RUN === 'true';
  const apiKey = process.env.PSI_API_KEY || null;

  if (!owner || !repo || !token) {
    throw new Error('REPO_OWNER, REPO_NAME, and GITHUB_TOKEN env vars are required');
  }
  if (config.require_psi_api_key !== false && !apiKey && !dryRun) {
    throw new Error('PSI_API_KEY is required for production runs. Set DRY_RUN=true to test without it.');
  }
  return {
    owner,
    repo,
    token,
    dryRun,
    apiKey,
    defaultBranch: config.default_branch,
    model: config.model,
  };
}

function buildSiteBase(config, owner, repo) {
  const configured = config.site_url || `https://${config.default_branch}--${repo}--${owner}.aem.page`;
  return configured.replace(/\/$/, '');
}

function buildURL(siteBase, path) {
  return new URL(path, `${siteBase}/`).toString();
}

function buildPRBody(regression, result, diagnosisResult) {
  const verified = result?.success;
  const statusIcon = verified ? '✅' : '⚠️';

  let body = `## ⚡ Performance Regression ${verified ? 'Fixed' : 'Detected'}\n\n`;
  if (regression.reasons?.length) {
    body += '### Trigger Reasons\n';
    regression.reasons.forEach((reason) => {
      body += `- ${reason}\n`;
    });
    body += '\n';
  }
  body += '| Metric | Baseline | Current | Delta |\n';
  body += '|--------|----------|---------|-------|\n';
  const baselineLCP = regression.baseline_lcp_ms == null ? 'n/a' : `${regression.baseline_lcp_ms}ms`;
  const scoreDelta = regression.score_delta > 0 ? `-${regression.score_delta}` : 'n/a';
  const lcpDelta = regression.lcp_delta_ms > 0 ? `+${regression.lcp_delta_ms}ms` : 'n/a';
  body += `| LCP | ${baselineLCP} | ${regression.current_lcp_ms}ms | ${lcpDelta} |\n`;
  body += `| INP | n/a | ${regression.current_inp_ms}ms | n/a |\n`;
  body += `| CLS | n/a | ${regression.current_cls} | n/a |\n`;
  body += `| Score | ${regression.baseline_score ?? 'n/a'} | ${regression.current_score ?? 'n/a'} | ${scoreDelta} |\n\n`;
  body += `**Diagnosis:** ${diagnosisResult.diagnosis}\n\n`;
  body += `**Root Cause:** ${diagnosisResult.rootCause}\n\n`;

  if (result?.previewURL) {
    body += '### Verification\n';
    body += `- Preview: ${result.previewURL}\n`;
    if (result.previewLCP != null) {
      body += `- Preview LCP: **${result.previewLCP}ms ${statusIcon}**\n`;
      body += `- Preview Score: **${result.previewScore} ${statusIcon}**\n`;
    }
    if (result.reason) body += `- Note: ${result.reason}\n`;
    body += '\n';
  }

  body += '\n---\n*Generated by perf-regression agent. Human review required before merging.*';
  return body;
}

async function handleRegression(regression, commits, diffs, config, context) {
  const {
    owner, repo, token, dryRun,
  } = context;
  const urlPath = new URL(regression.url).pathname;

  let diagnosisResult = { diagnosis: 'AI diagnosis unavailable', rootCause: 'unknown', confidence: 'low' };
  if (config.ai_diagnosis_enabled === false) {
    diagnosisResult = {
      diagnosis: 'AI diagnosis disabled by configuration',
      rootCause: 'unknown',
      confidence: 'low',
    };
  } else {
    try {
      diagnosisResult = await diagnose(
        regression,
        commits,
        diffs,
        token,
        context.model,
        config.lookback_hours,
      );
      console.log(`[diagnose] confidence=${diagnosisResult.confidence}: ${diagnosisResult.diagnosis}`);
    } catch (err) {
      console.error(`[diagnose] Failed: ${err.message}`);
    }
  }

  let result;
  if (config.auto_fix_enabled && diagnosisResult.confidence === 'high' && diagnosisResult.fix) {
    const titlePrefix = `perf: CWV regression on ${urlPath}`;
    const alreadyOpen = await checkOpenPRs(owner, repo, { titlePrefix }, token);
    if (alreadyOpen) {
      console.log(`[perf-agent] Open perf-regression PR already exists for ${urlPath}.`);
      return;
    }

    try {
      result = await applyAndVerify(diagnosisResult.fix, regression, {
        ...context,
        strategy: config.strategy,
        defaultBranch: config.default_branch,
        previewTimeoutMs: config.preview_poll.timeout_ms,
        previewPollMs: config.preview_poll.interval_ms,
      });
      console.log(`[fix] branch=${result.branch} verified=${result.success}`);
    } catch (err) {
      console.error(`[fix] Failed: ${err.message}`);
      result = { success: false, reason: err.message };
    }

    const status = result?.success ? 'fix verified' : 'fix unverified';
    const title = `perf: CWV regression on ${urlPath} (${status})`;
    const body = buildPRBody(regression, result, diagnosisResult);

    if (!dryRun && result?.branch) {
      const pr = await createPR(owner, repo, {
        title,
        body,
        head: result.branch,
        base: config.default_branch,
        labels: [PERF_PR_LABEL],
      }, token);
      console.log(`[perf-agent] PR created: ${pr.url}`);
    } else {
      console.log(`[DRY RUN] Would open PR: "${title}"`);
    }
  } else {
    const title = `perf: CWV regression on ${urlPath} — needs human review`;
    const body = buildPRBody(regression, null, diagnosisResult);
    const issueAlreadyOpen = await checkOpenIssues(owner, repo, {
      label: HUMAN_REVIEW_LABEL,
      title,
    }, token);
    if (issueAlreadyOpen) {
      console.log(`[perf-agent] Open issue already exists: "${title}"`);
      return;
    }

    if (!dryRun) {
      const issue = await createIssue(owner, repo, {
        title,
        body,
        labels: [HUMAN_REVIEW_LABEL],
      }, token);
      console.log(`[perf-agent] Issue created: ${issue.url}`);
    } else {
      console.log(`[DRY RUN] Would open issue: "${title}"`);
    }
  }
}

async function main() {
  const config = loadConfig();
  const context = buildContext(config);
  const {
    owner, repo, token, dryRun, apiKey,
  } = context;
  const siteBase = buildSiteBase(config, owner, repo);
  const updateBaseline = process.argv.includes('--update-baseline');

  console.log(`[perf-agent] site=${siteBase} paths=${config.paths.join(',')}${dryRun ? ' DRY_RUN' : ''}`);

  const currentScores = await Promise.all(
    config.paths.map((p) => fetchPSI(buildURL(siteBase, p), config.strategy, apiKey)),
  );
  currentScores.forEach((s) => console.log(`[psi] ${s.url} score=${s.score} lcp=${s.lcp_ms}ms`));

  if (updateBaseline) {
    saveBaseline(BASELINE_PATH, currentScores);
    console.log('[perf-agent] Baseline updated. Commit .github/baselines/performance.json to persist.');
    return;
  }

  const baseline = loadBaseline(BASELINE_PATH);

  if (Object.keys(baseline).length === 0) {
    console.log('[perf-agent] No baseline found — saving current scores as baseline.');
    if (!dryRun) saveBaseline(BASELINE_PATH, currentScores);
    console.log('[perf-agent] Commit .github/baselines/performance.json to start tracking regressions.');
    return;
  }

  const regressions = detectRegressions(currentScores, baseline, config.thresholds);

  if (regressions.length === 0) {
    console.log('[perf-agent] No regressions detected. All scores within threshold.');
    return;
  }

  console.log(`[perf-agent] ${regressions.length} regression(s) detected.`);

  const since = new Date(Date.now() - config.lookback_hours * 3_600_000).toISOString();
  const commits = await getRecentCommits(owner, repo, since, token);
  const diffs = await Promise.all(commits.map((c) => getCommitDiff(owner, repo, c.sha, token)));
  console.log(`[perf-agent] ${commits.length} commit(s) in ${config.lookback_hours}h lookback window.`);

  for (const regression of regressions) {
    console.log(`[regression] ${regression.url} LCP +${regression.lcp_delta_ms}ms score -${regression.score_delta}`);
    // eslint-disable-next-line no-await-in-loop
    await handleRegression(regression, commits, diffs, config, context);
  }
}

main().catch((err) => {
  console.error(`[perf-agent] Fatal: ${err.message}`);
  process.exit(1);
});
