import { readFileSync } from 'fs';
import { fetchPSI } from './psi.js';
import { loadBaseline, saveBaseline, detectRegressions } from './baseline.js';
import { diagnose } from './diagnose.js';
import { applyAndVerify } from './fix.js';
import {
  getRecentCommits,
  getCommitDiff,
  checkOpenPRs,
  createPR,
  createIssue,
} from './github-api.js';

const BASELINE_PATH = '.github/baselines/performance.json';
const CONFIG_PATH = 'perf-agent.config.json';

function loadConfig() {
  return JSON.parse(readFileSync(CONFIG_PATH, 'utf8'));
}

function buildContext() {
  const owner = process.env.REPO_OWNER;
  const repo = process.env.REPO_NAME;
  const token = process.env.GITHUB_TOKEN;
  const dryRun = process.env.DRY_RUN === 'true';
  const apiKey = process.env.PSI_API_KEY || null;

  if (!owner || !repo || !token) {
    throw new Error('REPO_OWNER, REPO_NAME, and GITHUB_TOKEN env vars are required');
  }
  return {
    owner, repo, token, dryRun, apiKey,
  };
}

function buildPRBody(regression, result, diagnosisResult) {
  const verified = result?.success;
  const statusIcon = verified ? '✅' : '⚠️';

  let body = `## ⚡ Performance Regression ${verified ? 'Fixed' : 'Detected'}\n\n`;
  body += '| Metric | Baseline | Current | Delta |\n';
  body += '|--------|----------|---------|-------|\n';
  body += `| LCP | ${regression.baseline_lcp_ms}ms | ${regression.current_lcp_ms}ms | +${regression.lcp_delta_ms}ms ❌ |\n`;
  body += `| Score | ${regression.baseline_score} | ${regression.current_score} | -${regression.score_delta} ❌ |\n\n`;
  body += `**Diagnosis:** ${diagnosisResult.diagnosis}\n\n`;
  body += `**Root Cause:** ${diagnosisResult.rootCause}\n\n`;

  if (result?.previewURL) {
    body += '### Verification\n';
    body += `- Preview: ${result.previewURL}\n`;
    if (result.previewLCP != null) {
      body += `- Preview LCP: **${result.previewLCP}ms ${statusIcon}**\n`;
      body += `- Preview Score: **${result.previewScore} ${statusIcon}**\n`;
    }
    if (result.reason) body += `- Note: ${result.reason}\n`;
    body += '\n';
  }

  body += '\n---\n*Generated by perf-regression agent. Human review required before merging.*';
  return body;
}

async function handleRegression(regression, commits, diffs, config, context) {
  const {
    owner, repo, token, dryRun,
  } = context;

  const alreadyOpen = await checkOpenPRs(owner, repo, 'perf-regression', token);
  if (alreadyOpen) {
    console.log('[perf-agent] Open perf-regression PR already exists — skipping duplicate.');
    return;
  }

  let diagnosisResult = { diagnosis: 'AI diagnosis unavailable', rootCause: 'unknown', confidence: 'low' };
  try {
    diagnosisResult = await diagnose(regression, commits, diffs, token);
    console.log(`[diagnose] confidence=${diagnosisResult.confidence}: ${diagnosisResult.diagnosis}`);
  } catch (err) {
    console.error(`[diagnose] Failed: ${err.message}`);
  }

  let result;
  if (diagnosisResult.confidence === 'high' && diagnosisResult.fix) {
    try {
      result = await applyAndVerify(diagnosisResult.fix, regression, {
        ...context,
        strategy: config.strategy,
      });
      console.log(`[fix] branch=${result.branch} verified=${result.success}`);
    } catch (err) {
      console.error(`[fix] Failed: ${err.message}`);
      result = { success: false, reason: err.message };
    }

    const urlPath = new URL(regression.url).pathname;
    const status = result?.success ? 'fix verified' : 'fix unverified';
    const title = `perf: CWV regression on ${urlPath} (${status})`;
    const body = buildPRBody(regression, result, diagnosisResult);

    if (!dryRun && result?.branch) {
      const pr = await createPR(owner, repo, {
        title, body, head: result.branch,
      }, token);
      console.log(`[perf-agent] PR created: ${pr.url}`);
    } else {
      console.log(`[DRY RUN] Would open PR: "${title}"`);
    }
  } else {
    const urlPath = new URL(regression.url).pathname;
    const title = `perf: CWV regression on ${urlPath} — needs human review`;
    const body = buildPRBody(regression, null, diagnosisResult);

    if (!dryRun) {
      const issue = await createIssue(owner, repo, {
        title,
        body,
        labels: ['perf-regression-needs-human'],
      }, token);
      console.log(`[perf-agent] Issue created: ${issue.url}`);
    } else {
      console.log(`[DRY RUN] Would open issue: "${title}"`);
    }
  }
}

async function main() {
  const config = loadConfig();
  const context = buildContext();
  const {
    owner, repo, token, dryRun, apiKey,
  } = context;
  const siteBase = `https://main--${repo}--${owner}.aem.page`;
  const updateBaseline = process.argv.includes('--update-baseline');

  console.log(`[perf-agent] site=${siteBase} paths=${config.paths.join(',')}${dryRun ? ' DRY_RUN' : ''}`);

  const currentScores = await Promise.all(
    config.paths.map((p) => fetchPSI(`${siteBase}${p}`, config.strategy, apiKey)),
  );
  currentScores.forEach((s) => console.log(`[psi] ${s.url} score=${s.score} lcp=${s.lcp_ms}ms`));

  if (updateBaseline) {
    saveBaseline(BASELINE_PATH, currentScores);
    console.log('[perf-agent] Baseline updated. Commit .github/baselines/performance.json to persist.');
    return;
  }

  const baseline = loadBaseline(BASELINE_PATH);

  if (Object.keys(baseline).length === 0) {
    console.log('[perf-agent] No baseline found — saving current scores as baseline.');
    if (!dryRun) saveBaseline(BASELINE_PATH, currentScores);
    console.log('[perf-agent] Commit .github/baselines/performance.json to start tracking regressions.');
    return;
  }

  const regressions = detectRegressions(currentScores, baseline, config.thresholds);

  if (regressions.length === 0) {
    console.log('[perf-agent] No regressions detected. All scores within threshold.');
    return;
  }

  console.log(`[perf-agent] ${regressions.length} regression(s) detected.`);

  const since = new Date(Date.now() - config.lookback_hours * 3_600_000).toISOString();
  const commits = await getRecentCommits(owner, repo, since, token);
  const diffs = await Promise.all(commits.map((c) => getCommitDiff(owner, repo, c.sha, token)));
  console.log(`[perf-agent] ${commits.length} commit(s) in ${config.lookback_hours}h lookback window.`);

  for (const regression of regressions) {
    console.log(`[regression] ${regression.url} LCP +${regression.lcp_delta_ms}ms score -${regression.score_delta}`);
    // eslint-disable-next-line no-await-in-loop
    await handleRegression(regression, commits, diffs, config, context);
  }
}

main().catch((err) => {
  console.error(`[perf-agent] Fatal: ${err.message}`);
  process.exit(1);
});
